name: Run unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.9"
          - python-version: "3.10"
          - python-version: "3.11"
          - python-version: "3.12"
    steps:
      # Check out
      - uses: actions/checkout@v4
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          cache: pip
      # Install dependencies
      - run: |
          python -m pip install -U pip==24.0
          python -m pip install -r requirements.txt
      # Run unit tests
      - name: Run unit tests
        run: |
          python -m pip install -e "${{ github.workspace }}"
          pytest -v -s "${{ github.workspace }}/tests"
